version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: .
    command: bash -c "
      ./wait-for-it.sh db:5432 --
      && python manage.py sorcery upgrade
      && python manage.py create_user
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    environment:
      - PSQLHOST=db
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
volumes:
  postgres_data: