"""
Add unique constraint to email

Revision ID: 062bfb7396e1
Revises: 479caa40957b
Create Date: 2019-12-22 20:58:10.737658
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062bfb7396e1'
down_revision = '479caa40957b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
